version: '3.1'

services:
  alesar_db:
    container_name: contactsinfo
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oracle
      MYSQL_USER: root
      MYSQL_PASSWORD: oracle
      MYSQL_DATABASE: alesar.contactsinfo
    ports:
      - 3307:3306

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
